import os
import cloudconvert
from app.core.config import settings

# this file defines the function that interacts with the CloudConvert API to perform file conversions
# based on the plan generated by the planner.

# _configure function sets up the CloudConvert API client with the API key from settings,
def _configure():
    key = settings.CLOUDCONVERT_API_KEY
    if not key or key in ("YOUR_CLOUDCONVERT_API_KEY", "YOUR_CLOUDCONVERT_KEY"):
        raise RuntimeError("CLOUDCONVERT_API_KEY missing or placeholder in .env")
    cloudconvert.configure(api_key=key, sandbox=False)


def run_cloudconvert(input_path: str, output_path: str, output_type: str, params: dict, max_runtime_sec: int = 180):
    """
    Convert input_path -> output_type using CloudConvert (API v2 SDK) and save to output_path.
    Raises RuntimeError with readable message on failure.
    """
    _configure()

    input_format = os.path.splitext(input_path)[1].lstrip(".").lower()

    job = cloudconvert.Job.create(payload={
        "tasks": {
            "upload-task": {"operation": "import/upload"},
            "convert-task": {
                "operation": "convert",
                "input": "upload-task",
                "input_format": input_format,
                "output_format": output_type,
                "options": {
                    **({"dpi": int(params["dpi"])} if isinstance(params, dict) and "dpi" in params else {}),
                    **({"page_size": params["page_size"]} if isinstance(params, dict) and "page_size" in params else {}),
                    **({"fit_mode": params["fit_mode"]} if isinstance(params, dict) and "fit_mode" in params else {}),
                },
            },
            "export-task": {"operation": "export/url", "input": "convert-task"},
        }
    })

    upload_task_id = None
    export_task_id = None
    for t in job.get("tasks", []):
        if t.get("name") == "upload-task":
            upload_task_id = t.get("id")
        elif t.get("name") == "export-task":
            export_task_id = t.get("id")

    if not upload_task_id or not export_task_id:
        raise RuntimeError(f"CloudConvert job missing task IDs. Job response: {job}")

    upload_task = cloudconvert.Task.find(id=upload_task_id)
    cloudconvert.Task.upload(file_name=input_path, task=upload_task)

    res = cloudconvert.Task.wait(id=export_task_id)
    if not res:
        res = cloudconvert.Task.find(id=export_task_id)

    status = res.get("status")
    if status != "finished":
        raise RuntimeError(f"CloudConvert failed (status={status}). Response: {res}")

    result = res.get("result") or {}
    files = result.get("files") or []
    if not files:
        raise RuntimeError(f"CloudConvert export produced no files. Response: {res}")

    url = (files[0] or {}).get("url")
    if not url:
        raise RuntimeError(f"CloudConvert export missing file URL. Response: {res}")

    cloudconvert.download(filename=output_path, url=url)
